spring:
  datasource:
    url: jdbc:mysql://localhost:3306/query_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8070