spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cqrs_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8070